USE majorplan;

CREATE TABLE MAJOR (
	MajorID INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (MajorID),
    MajorName varchar(200)
);

CREATE TABLE TAG (
	TagID INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (TagID),
    TagName varchar(200)
);

CREATE TABLE MAJOR_TAG (
	MajorTagID INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (MajorTagID),
    TagID INT,
    FOREIGN KEY (TagID) REFERENCES TAG(TagID),
    MajorID INT,
    FOREIGN KEY (MajorID) REFERENCES MAJOR(MajorID)
);

CREATE TABLE REQ (
	ReqID INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (ReqID),
    ReqName varchar(100),
    ReqDesc varchar(100)
);

CREATE TABLE MAJOR_REQ (
	MajorReqID INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (MajorReqID),
    ReqID INT,
    FOREIGN KEY (ReqID) REFERENCES REQ(ReqID),
    MajorID INT,
    FOREIGN KEY (MajorID) REFERENCES MAJOR(MajorID)
);

CREATE TABLE COURSE (
	CourseID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (CourseID),
    CourseName varchar(100),
    CourseDesc varchar(100),
    MinGrade FLOAT,
    PrereqID INT,
    FOREIGN KEY (PrereqID) REFERENCES COURSE(CourseID)
);

CREATE TABLE MAJOR_COURSE (
	MajorCourseID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (MajorCourseID),
    CourseID INT,
    FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID),
    MajorID INT,
    FOREIGN KEY (MajorID) REFERENCES MAJOR(MajorID)
);
